#!/bin/sh

set -eu

if ! cargo fmt -- --check --quiet
then
    echo "There are some code style issues."
    echo "Running `cargo fmt` to fix them."
    if ! cargo fmt
    then
        echo "Failed to run `cargo fmt`."
        exit 1
    fi
    exit 1
fi

if ! cargo clippy --all-targets -- -A clippy::pedantic -D warnings 
then
    echo "There are some clippy issues."
    exit 1
fi
# Ignore the `binary_rewrite_test` which takes a minute.
if ! cargo nextest run --tests  -E 'not test(/.*recomp/)'
then
    echo "There are some test issues."
    exit 1
fi

exit 0
